spring:
  thymeleaf:
    #关闭缓存
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: hsp
    # 数据库连接池
    hikari:
      #连接池名
      pool-name: Hsp_Hikari_Poll
      #最小空闲连接
      minimum-idle: 5
      #空闲连接存活最大时间，默认 60000(10 分钟)
      idle-timeout: 60000
      # 最大连接数，默认是 10
      maximum-pool-size: 10
      #从连接池返回来的连接自动提交
      auto-commit: true
      #连接最大存活时间。0 表示永久存活，默认 180000（30 分钟）
      max-lifetime: 180000
      #连接超时时间，默认 30000（30 秒）
      connection-timeout: 30000
      #测试连接是否可用的查询语句
      connection-test-query: select 1

  #配置redis
  redis:
    host: 192.168.174.140
    port: 6379
    database: 0
    timeout: 10000ms
    lettuce:
      pool:
        max-active: 16
        max-wait: 10000ms
        max-idle: 200
        min-idle: 5

  rabbitmq:
    #安装兔子的虚拟机的ip地址
    host: 192.168.174.140
    username: guest
    password: guest
    virtual-host: /
    port: 5672
    listener:
      simple:
        #消费者的最小数量
        concurrency: 10
        #消费者的最大数量
        max-concurrency: 10
        #限制消费者每次只能处理一条消息，处理完才能继续下一条消息
        prefetch: 1
        #启动时是否默认启动兔子
        auto-startup: true
        #被拒绝后是否重新进入队列
        default-requeue-rejected: true
    template:
      retry:
        #启用重试机制,默认false
        enabled: true
        #设置初始化的重试时间间隔
        initial-interval: 1000ms
        #重试最大次数
        max-attempts: 3
        #重试最大时间间隔
        max-interval: 10000ms
        #重试时间间隔的乘数
        multiplier: 1

#mybatis-plus 配置
mybatis-plus:
  #配置 mapper.xml 映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  #配置 mybatis 数据返回类型别名
  type-aliases-package: com.hspedu.seckill.pojo
#mybatis sql 打印
logging:
  level:
    com.hspedu.seckill.mapper: debug
  #redis 配置
